name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install

      - name: Linting
        run:  npx eslint .

      - name: Build
        run: npm run build

      # - name: Test
      #   run: npm test ##commented out the tests since there are none 
